FROM ubuntu:vivid
MAINTAINER 42nerds - Inh. Julian Kaffke <info@42nerds.com>

# Update apt cache and upgrade
RUN apt-get update && apt-get upgrade

# Install common libraries
RUN apt-get install -y curl wget git vim